# Generated by Django 2.2.1 on 2019-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('production_year', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('mass', models.PositiveIntegerField()),
                ('load_capacity', models.PositiveIntegerField()),
                ('axes_number', models.PositiveIntegerField()),
            ],
        ),
    ]
