# Generated by Django 2.2.1 on 2019-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.PositiveIntegerField()),
                ('num', models.PositiveIntegerField()),
                ('coord', models.CharField(max_length=128)),
            ],
        ),
    ]
